### ISSUE TITLE
BlankStore crashes 

### ISSUE THREAD

**Issue by zarere** [mar-v-in/BlankStore#17]
I'm using

This ROM
http://forum.xda-developers.com/galaxy-s3/development/rom-archidroid-v2-4-6-power-hands-t2354859

And Blankstore crashes with this:
```

I/ActivityManager( 2425): Start proc 6727:com.android.vending/u0a64 for activity com.android.vending/.BlankActivity
D/BlankActivity( 6727): Accounts: 0
D/BlankActivity( 6727): Need Account to work!
I/Timeline( 6727): Timeline: Activity_launch_request id:com.android.vending time:1200762
D/BlankActivity( 6727): Accounts initialized.
D/BlankActivity( 6727): BlankStore initialized.
D/OpenGLRenderer( 6727): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas   ( 6727): Validating map...
D/libEGL  ( 6727): loaded /system/lib/egl/libEGL_mali.so
D/libEGL  ( 6727): loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL  ( 6727): loaded /system/lib/egl/libGLESv2_mali.so
E/        ( 6727): Device driver API match
E/        ( 6727): Device driver API version: 29
E/        ( 6727): User space API version: 29 
E/        ( 6727): mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Tue Jul 22 19:59:34 KST 2014 
I/OpenGLRenderer( 6727): Initialized EGL, version 1.4
D/OpenGLRenderer( 6727): Enabling debug mode 0
I/Timeline( 6727): Timeline: Activity_idle id: android.os.BinderProxy@1c2020b8 time:1201178
I/Timeline( 6727): Timeline: Activity_launch_request id:com.android.vending time:1280451
D/BlankActivity( 6727): Accounts: 1
D/BlankActivity( 6727): Account: com.android.vending.account.Account{type="GooglePlay", login="*e*t*5*7*e*t*5*7@gmail.com", password="********", androidId="*c*f*5*0*0*5*4*4", deviceName="m0", sdkVersion="22", operatorAlpha="VIVACOM", operatorNumeric="28403"}
D/BlankActivity( 6727): Accounts initialized.
D/BlankActivity( 6727): BlankStore initialized.
I/Timeline( 6727): Timeline: Activity_idle id: android.os.BinderProxy@1b288a60 time:1280707
D/DefaultGooglePlayConnection( 6727): queryAppsByName[extended=false]: pname:com.android.providers.telephony [START]
E/AndroidRuntime( 6727): FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime( 6727): Process: com.android.vending, PID: 6727
E/AndroidRuntime( 6727): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 6727): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 6727): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 6727): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 6727): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 6727): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 6727): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 6727): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 6727): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 6727): Caused by: com.gc.android.market.api.Tools$HttpException: HTTP Code 404 : Error=UNKNOWN_ERR
E/AndroidRuntime( 6727): 
E/AndroidRuntime( 6727): 	at com.gc.android.market.api.Tools.postUrl(Tools.java:66)
E/AndroidRuntime( 6727): 	at com.gc.android.market.api.MarketSession.login(MarketSession.java:352)
E/AndroidRuntime( 6727): 	at com.gc.android.market.api.MarketSession.login(MarketSession.java:334)
E/AndroidRuntime( 6727): 	at com.android.vending.google.GooglePlayConnection.openConnectionSynced(GooglePlayConnection.java:131)
E/AndroidRuntime( 6727): 	at com.android.vending.google.DefaultGooglePlayConnection.startAppsRequestSynced(DefaultGooglePlayConnection.java:319)
E/AndroidRuntime( 6727): 	at com.android.vending.google.DefaultGooglePlayConnection.queryAppsByName(DefaultGooglePlayConnection.java:236)
E/AndroidRuntime( 6727): 	at com.android.vending.tasks.AppsTask.doInBackground(AppsTask.java:50)
E/AndroidRuntime( 6727): 	at com.android.vending.tasks.AppsTask.doInBackground(AppsTask.java:10)
E/AndroidRuntime( 6727): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 6727): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 6727): 	... 4 more
I/Process ( 6727): Sending signal. PID: 6727 SIG: 9
W/InputMethodManagerService( 2425): Got RemoteException sending setActive(false) notification to pid 6727 uid 10064
I/ActivityManager( 2425): Process com.android.vending (pid 6727) has died

```

Please advise.

**Comment by zarere** [comment]
The solution was to add a standard google account on the phone(accounts->add->google) and then create the same account in BlankStore app itself and sync it.After that the standard google account can be deleted and the BlankStore one is continuing working fine.
