### ISSUE TITLE
BlankStore crashing most of the time since ~1 month

### ISSUE THREAD

**Issue by ArchangeGabriel** [mar-v-in/BlankStore#22]
When I click on installed apps, try searching an app or sometimes when clicking on update, BlankStore crash. I would say like 9 times over 10.

logcat excerpt:
```
07-02 18:33:03.426 31584 31703 D DefaultGooglePlayConnection: queryAppsByName[extended=false]: pname:org.omnirom.omnijaws [START]
07-02 18:33:03.437 31584 31703 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-02 18:33:03.721 31584 31703 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
07-02 18:33:03.721 31584 31703 E AndroidRuntime: Process: com.android.vending, PID: 31584
07-02 18:33:03.721 31584 31703 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
07-02 18:33:03.721 31584 31703 E AndroidRuntime: Caused by: com.gc.android.market.api.LoginException: The login request used a username or password that is not recognized.
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at com.gc.android.market.api.MarketSession.login(MarketSession.java:384)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at com.gc.android.market.api.MarketSession.login(MarketSession.java:334)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at com.android.vending.google.GooglePlayConnection.openConnectionSynced(GooglePlayConnection.java:131)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at com.android.vending.google.DefaultGooglePlayConnection.startAppsRequestSynced(DefaultGooglePlayConnection.java:319)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at com.android.vending.google.DefaultGooglePlayConnection.queryAppsByName(DefaultGooglePlayConnection.java:236)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at com.android.vending.tasks.AppsTask.doInBackground(AppsTask.java:50)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at com.android.vending.tasks.AppsTask.doInBackground(AppsTask.java:10)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-02 18:33:03.721 31584 31703 E AndroidRuntime:        ... 4 more
07-02 18:33:03.746  2387  3409 W ActivityManager:   Force finishing activity com.android.vending/.BlankActivity
07-02 18:33:03.765  2387  3409 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.am.AppErrors.crashApplicationInner:370 com.android.server.am.AppErrors.crashApplication:305 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:13549 com.android.server.am.ActivityManagerService.handleApplicationCrash:13531 
```

**Comment by ArchangeGabriel** [comment]
Apparently this is a Google-side change, also affecting similar apps: https://framagit.org/tuxicoman/googleplaydownloader/issues/12

**Comment by ArchangeGabriel** [comment]
This was fixed in Racoon: https://github.com/onyxbits/raccoon4/commit/0c2196be000bed01c8c0c8c72e955355aa9bf80d

I know nothing when it comes to Java/Android dev, but could someone with a bit of knowledge take a look at this and port this change in BlankStore?
