### ISSUE TITLE
BlankStore crashes when i press on "Installed Apps" or search something.

### ISSUE THREAD

**Issue by pandavova** [mar-v-in/BlankStore#24]
Well, i am using a S5 Neo with Xposed (FakeGApps), Magisk and microG.
BlankStore has the permissions, but it still crashes. I read here that for some it works without Wifi, but it crashes still without Wifi.

What could i do to fix this?

Vova

**Comment by JonnyTech** [comment]
Which version of microG, latest [0.2.4-105](https://microg.org/fdroid/repo/com.google.android.gms-11675464.apk)? Can you provide a log and more details?

**Comment by pandavova** [comment]
Yeah, 0.2.4-105-gf289a13...
How could i do a log? adb?

EDIT:
09-11 19:20:14.144 14167 18760 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
09-11 19:20:14.144 14167 18760 E AndroidRuntime: Process: com.android.vending, PID: 14167
09-11 19:20:14.144 14167 18760 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:309)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
09-11 19:20:14.144 14167 18760 E AndroidRuntime: Caused by: com.gc.android.market.api.LoginException: **The login request used a username or password that is not recognized.**
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at com.gc.android.market.api.MarketSession.login(MarketSession.java:384)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at com.gc.android.market.api.MarketSession.login(MarketSession.java:334)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at com.android.vending.google.GooglePlayConnection.openConnectionSynced(GooglePlayConnection.java:131)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at com.android.vending.google.DefaultGooglePlayConnection.startAppsRequestSynced(DefaultGooglePlayConnection.java:319)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at com.android.vending.google.DefaultGooglePlayConnection.queryAppsByName(DefaultGooglePlayConnection.java:236)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at com.android.vending.tasks.AppsTask.doInBackground(AppsTask.java:50)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at com.android.vending.tasks.AppsTask.doInBackground(AppsTask.java:10)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-11 19:20:14.144 14167 18760 E AndroidRuntime:        ... 4 more

Hmmm, but i tryed it 10 times and even typed my password slowly...
My Email is correct too... :/

**Comment by ArchangeGabriel** [comment]
This is expected, BlankStore is currently broken, see https://github.com/mar-v-in/BlankStore/issues/22.

You can take a look at YalpStore in the meantime.
