### ISSUE TITLE
BlankStore crash: ClientLogin deprecated, OAUTH required

### ISSUE THREAD

**Issue by bonanza123** [mar-v-in/BlankStore#7]
For me BlankStore crashes upon loading installed or searching apps. Here some log:

```
10-21 09:35:17.047 I/ActivityManager(12618): Displayed com.android.vending/.BlankActivity: +353ms
10-21 09:35:17.932 E/Parcel  (18289): Reading a NULL string not supported here.
10-21 09:35:17.959 D/DefaultGooglePlayConnection(18289): queryAppsByName[extended=false]: pname:net.nanabit.callconfirm [START]
10-21 09:35:18.541 E/AndroidRuntime(18289): FATAL EXCEPTION: AsyncTask #1
10-21 09:35:18.541 E/AndroidRuntime(18289): Process: com.android.vending, PID: 18289
10-21 09:35:18.541 E/AndroidRuntime(18289): java.lang.RuntimeException: An error occured while executing doInBackground()
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at java.lang.Thread.run(Thread.java:818)
10-21 09:35:18.541 E/AndroidRuntime(18289): Caused by: com.gc.android.market.api.Tools$HttpException: HTTP Code 404 : https://developers.google.com/accounts/docs/AuthForInstalledApps
10-21 09:35:18.541 E/AndroidRuntime(18289): 
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at com.gc.android.market.api.Tools.postUrl(Tools.java:66)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at com.gc.android.market.api.MarketSession.login(MarketSession.java:352)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at com.gc.android.market.api.MarketSession.login(MarketSession.java:334)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at com.android.vending.google.GooglePlayConnection.openConnectionSynced(GooglePlayConnection.java:131)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at com.android.vending.google.DefaultGooglePlayConnection.startAppsRequestSynced(DefaultGooglePlayConnection.java:319)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at com.android.vending.google.DefaultGooglePlayConnection.queryAppsByName(DefaultGooglePlayConnection.java:236)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at com.android.vending.tasks.AppsTask.doInBackground(AppsTask.java:50)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at com.android.vending.tasks.AppsTask.doInBackground(AppsTask.java:10)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-21 09:35:18.541 E/AndroidRuntime(18289): 	... 4 more
10-21 09:35:18.551 W/ActivityManager(12618):   Force finishing activity 1 com.android.vending/.BlankActivity
10-21 09:35:18.569 W/DropBoxManagerService(12618): Dropping: system_app_crash (1731 > 0 bytes)
```

Here some information about the issue: https://developers.google.com/identity/protocols/AuthForInstalledApps

**Comment by mar-v-in** [comment]
The documentation is crap, ClientLogin will always be there (at least for the next ~5 years), as it is used by Android internally since Android 2 and is still used in 6.0. I guess they just disabled the public API end point. Will check when at home, but probably this is a one line change.

We can not update to OAuth anyway: The access to play store is not provided as OAuth scope.

**Comment by YoranSys** [comment]
Hi, same problem here crashes.

**Comment by mar-v-in** [comment]
Version 0.7.3 of BlankStore should fix the issue.
